### ISSUE TITLE
consider adding an example for using this library

### ISSUE THREAD

**Issue by devoncarew** [rmsmith/tags#6]
Either in an `example` folder or in the readme?

**Comment by rmsmith** [comment]
Thanks for noticing :)

This library has evolved a lot from its original state, and I just recently removed an example that had little to do with the current code.  I'd like to make a `TodoMVC` or something similar but I probably won't have time to get to it for a while.

**Comment by rmsmith** [comment]
I'm going to close this issue.  This project has "finished" and I don't plan to do further work on it, so adding examples now might send the wrong message.  Thanks for the interest though!
